# All the SQLite files and metadata.csv are generated by
# a Snakemake workflow (mesh-workflow)
# https://github.com/rikenbit/mesh-workflow

# metadata.csv is finally saved in the AHMeSHDbs/inst/extdata/ directory.

# To generate Gene ID - MeSH ID correspondance table of 75 species,
# highly loaded calculations such as
# parsing 1.4 million rows of gene2accession,
# parsing 800 of PubMed XML files,
# and 3000 times of UBLAST
# are required.

# Hence using distributed computing environment such as
# Open Grid Engine or Slurm is highly recommended.

# For the details, see the README.md and workflow/*.smk of mesh-workflow